name: Minha primeira action

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run a command
        run: echo >> test
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Bump version and commit changes
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Bump version"
          git push

      - name: Create new Git tag
        run: |
          git tag -a v3$(node -p "require('./package.json').version") -m "Version $(node -p "require('./package.json').version")"
          git push origin --tags
