name: Upload Asset

on:
  push:
    tags:
      - 'v*'

jobs:
  upload_asset:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install requests
      run: pip install requests

    - name: Upload asset
      env:
        USERNAME: ${{ secrets.ASSET_LIBRARY_USERNAME }}
        PASSWORD: ${{ secrets.ASSET_LIBRARY_PASSWORD }}
        VERSION: 'godot4-v1.0.1'
        COMMIT_HASH: 'asd21dasd'
      run: |
        python push.py
